In [1]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
a = arange(3)
shape(a)

(3,)

In [7]:
a = array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

In [8]:
import numpy as np

In [9]:
a = np.array([[1,2],
           [3,4]], 
          dtype = np.uint8)

In [11]:
a.tostring() #转化为字符串：



'\x01\x02\x03\x04'

In [12]:
s = a.tostring()
a = np.fromstring(s, 
                  dtype=np.uint8)
a

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  This is separate from the ipykernel package so we can avoid doing imports until


array([1, 2, 3, 4], dtype=uint8)

In [14]:
#返回的数组是一维的，需要重新设定维度
a.shape = 2,2
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [15]:
np.arange(4)

array([0, 1, 2, 3])

In [16]:
np.arange(1.5, 2.1, 0.3)

array([1.5, 1.8, 2.1])